version: 2
registries:
  npm-registry-npm-pkg-github-com-navikt-data-catalog-components:
    type: npm-registry
    url: https://npm.pkg.github.com/@navikt/data-catalog-components
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_NAVIKT_DATA_CATALOG_COMPONENTS_TOKEN}}"
  npm-registry-npm-pkg-github-com-deetly-plotly-view:
    type: npm-registry
    url: https://npm.pkg.github.com/@deetly/plotly-view
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_DEETLY_PLOTLY_VIEW_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@navikt/sif-common-formik"
    versions:
    - 14.0.1
    - 15.3.2
    - 15.3.7
    - 15.4.0
    - 15.4.10
    - 15.4.5
    - 15.5.2
    - 17.0.2
    - 17.2.6
    - 17.4.1
    - 18.0.0
    - 18.0.1
    - 18.1.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: nav-frontend-popover
    versions:
    - 1.0.2
    - 1.1.1
  - dependency-name: nav-frontend-paneler-style
    versions:
    - 1.1.1
  - dependency-name: nav-frontend-lukknapp
    versions:
    - 1.1.1
  - dependency-name: nav-frontend-hjelpetekst-style
    versions:
    - 2.1.1
  - dependency-name: nav-frontend-modal
    versions:
    - 1.1.1
  - dependency-name: nav-frontend-stegindikator
    versions:
    - 1.1.1
  - dependency-name: nav-frontend-lenker-style
    versions:
    - 1.0.2
    - 1.1.1
  - dependency-name: nav-frontend-hjelpetekst
    versions:
    - 2.1.1
  - dependency-name: core-js
    versions:
    - 3.10.1
  - dependency-name: typescript
    versions:
    - 4.2.4
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: react-intl
    versions:
    - 5.10.19
    - 5.11.0
    - 5.12.0
    - 5.12.1
    - 5.12.3
    - 5.12.5
    - 5.13.0
    - 5.13.1
    - 5.13.2
    - 5.13.3
    - 5.13.4
    - 5.13.5
    - 5.15.3
    - 5.15.5
    - 5.15.7
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: react-dev-utils
    versions:
    - 11.0.4
  - dependency-name: nav-frontend-veilederpanel-style
    versions:
    - 1.0.2
    - 1.0.3
  - dependency-name: nav-frontend-popover-style
    versions:
    - 1.0.2
  - dependency-name: nav-frontend-tabs
    versions:
    - 1.0.2
  - dependency-name: nav-frontend-skjema-style
    versions:
    - 2.0.31
  - dependency-name: nav-frontend-typografi-style
    versions:
    - 1.0.32
    - 1.0.33
    - 1.0.34
  - dependency-name: nav-frontend-alertstriper-style
    versions:
    - 2.0.36
  - dependency-name: nav-frontend-spinner
    versions:
    - 2.0.16
  - dependency-name: nav-frontend-stegindikator-style
    versions:
    - 1.0.46
  - dependency-name: "@navikt/sif-common-core"
    versions:
    - 8.0.4
    - 8.1.1
  - dependency-name: nav-frontend-chevron
    versions:
    - 1.0.25
    - 1.0.27
  - dependency-name: nav-frontend-core
    versions:
    - 5.0.11
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.9
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  registries:
  - npm-registry-npm-pkg-github-com-navikt-data-catalog-components
  - npm-registry-npm-pkg-github-com-deetly-plotly-view
